import { defineField, defineType } from "sanity";

// Mirrors the Framer "Projects" collection field for field, in the same order.
export const project = defineType({
  name: "project",
  title: "Project",
  type: "document",
  groups: [
    { name: "main", title: "Project", default: true },
    { name: "case", title: "Case study" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "title", title: "Project title", type: "string", group: "main", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "main",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "cover",
      title: "Cover image",
      type: "image",
      group: "main",
      options: { hotspot: true },
      description: "Shown on the home feed, the projects index and as the hero. Its proportions set the card size.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "video",
      title: "Video",
      type: "file",
      group: "main",
      options: { accept: "video/*" },
      description: "Optional. Plays in place of the cover image (the cover stays as the poster).",
    }),
    defineField({
      name: "projectType",
      title: "Project type",
      type: "string",
      group: "main",
      options: { list: ["Client project", "Framer template", "Personal project"], layout: "radio" },
      initialValue: "Client project",
      validation: (r) => r.required(),
    }),
    defineField({ name: "year", title: "Year", type: "string", group: "main", validation: (r) => r.required() }),
    defineField({ name: "industry", title: "Industry", type: "string", group: "main", validation: (r) => r.required() }),
    defineField({
      name: "services",
      title: "Services",
      type: "array",
      of: [{ type: "string" }],
      group: "main",
      options: { layout: "tags" },
      description: "One per line, e.g. Web Design, Framer Development.",
    }),
    defineField({
      name: "tools",
      title: "Tools",
      type: "array",
      of: [{ type: "string" }],
      group: "main",
      options: { layout: "tags" },
    }),
    defineField({ name: "website", title: "Website link", type: "url", group: "main" }),
    defineField({ name: "contra", title: "Contra link", type: "url", group: "main" }),
    defineField({ name: "marketplace", title: "Marketplace link", type: "url", group: "main" }),
    defineField({
      name: "featured",
      title: "Featured",
      type: "boolean",
      group: "main",
      initialValue: false,
      description: "Featured projects appear in the home page feed.",
    }),
    defineField({
      name: "order",
      title: "Order",
      type: "number",
      group: "main",
      description: "Lower numbers come first on the home feed and projects index.",
    }),
    defineField({
      name: "shortDescription",
      title: "Short description",
      type: "text",
      rows: 3,
      group: "main",
      validation: (r) => r.required(),
    }),

    defineField({ name: "about", title: "About project", type: "richText", group: "case" }),
    defineField({ name: "largeImage1", title: "Large image 1", type: "image", group: "case", options: { hotspot: true } }),
    defineField({ name: "approach", title: "The approach", type: "richText", group: "case" }),
    defineField({ name: "largeImage2", title: "Large image 2", type: "image", group: "case", options: { hotspot: true } }),
    defineField({ name: "smallImage1", title: "Small image 1", type: "image", group: "case", options: { hotspot: true } }),
    defineField({ name: "smallImage2", title: "Small image 2", type: "image", group: "case", options: { hotspot: true } }),
    defineField({ name: "outcome", title: "The outcome", type: "richText", group: "case" }),
    defineField({ name: "largeImage3", title: "Large image 3", type: "image", group: "case", options: { hotspot: true } }),

    defineField({
      name: "seoDescription",
      title: "SEO description",
      type: "text",
      rows: 3,
      group: "seo",
      description: "Optional, max 160 characters. Leave empty to generate one from the fields above.",
      validation: (r) => r.max(160),
    }),
  ],
  orderings: [{ title: "Manual order", name: "order", by: [{ field: "order", direction: "asc" }] }],
  preview: {
    select: { title: "title", subtitle: "industry", media: "cover", featured: "featured" },
    prepare: ({ title, subtitle, media, featured }) => ({ title, subtitle: `${subtitle ?? ""}${featured ? " · Featured" : ""}`, media }),
  },
});
